#include <TempSensor_i_adapter.h>

Unit bc_BuildingControl_TempSensor_i_adapter_initialiseArchitecture() {
  bc_BuildingControlDemo_i_Instance_tcp_tempSensor_tempSensor_initialiseArchitecture(SF_LAST);
}

Unit bc_BuildingControl_TempSensor_i_adapter_initialiseEntryPoint() {
  bc_BuildingControlDemo_i_Instance_tcp_tempSensor_tempSensor_initialiseEntryPoint(SF_LAST);
}

Unit bc_BuildingControl_TempSensor_i_adapter_computeEntryPoint() {
  bc_BuildingControlDemo_i_Instance_tcp_tempSensor_tempSensor_computeEntryPoint(SF_LAST);
}
